# Deployment values used by templates.
dep:
  appName: argo-image-updater-app
  image: ghalamif/imagefaps:2.0.1
  replicas: 1
# Service values for ports.
svc:
  port: 3200
  targetPort: 80
# Image values for the container.
image: 
  name: ghalamif/imagefaps:2.0.1
  repository: ghalamif/imagefaps
  tag: 2.0.1
  pullPolicy: IfNotPresent





    
