# Base Deployment used for rollout comparisons.
# Defines two replicas of the base app image.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: base-app
  template:
    metadata:
      labels:
        app: base-app
    spec:
      containers:
      - name: base-app
        image: ghalamif/imagefaps:0.1.0
        resources:
          limits:
            memory: "26Mi"
            cpu: "5m"
        ports:
        - containerPort: 80
