# Service for the base deployment used with Argo Rollouts examples.
# You can switch to LoadBalancer or NodePort if needed.
apiVersion: v1
kind: Service
metadata:
  name: base-app-service
spec:
  #type: LoadBalancer
  selector:
    app: base-app
  ports:
    - port: 3200
      targetPort: 80
      #nodePort: 30020
