---
# Base kustomization: lists core resources and adds name prefix/suffix.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- deployment.yaml


namePrefix: v1-
nameSuffix: -fau
