# Service for the hooks demo deployment.
# Exposes the app on port 3200 to the selected pods.
apiVersion: v1
kind: Service
metadata:
  name: argo-hooks-service
spec:
  #type: LoadBalancer
  selector:
    app: argo-hooks
  ports:
    - port: 3200
      targetPort: 80
      #nodePort: 30020
