# Service for the web-hook demo deployment.
# Exposes the app on port 3200.
apiVersion: v1
kind: Service
metadata:
  name: pr-argo-hooks-service
spec:
  #type: LoadBalancer
  selector:
    app: pr-argo-hooks
  ports:
    - port: 3200
      targetPort: 80
      #nodePort: 30020
