# Helm template for the demo Deployment.
# Pulls values for replicas, labels, and image.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-helm-app-deployment
spec:
  replicas: {{ .Values.dep.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.dep.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.dep.appName }}
    spec:
      containers:
        - name: {{ .Values.dep.appName }}
          image: {{ .Values.dep.image }}
          resources:
            limits:
              memory: "26Mi"
              cpu: "5m"
          ports:
            - containerPort: 80
