# Helm template for the demo Service.
# Uses values for port mapping and selector.
apiVersion: v1
kind: Service
metadata:
  name: base-helm-app-service
spec:
  selector:
    app: {{ .Values.dep.appName }}
  ports:
    - port: {{ .Values.svc.port }}
      targetPort: {{ .Values.svc.targetPort }}
