# Service for the cascade deletion demo app.
# Selects app pods and exposes port 3200.
apiVersion: v1
kind: Service
metadata:
  name: pr-cascade-del-service
spec:
  #type: LoadBalancer
  selector:
    app: pr-cascade-del
  ports:
    - port: 3200
      targetPort: 80
      #nodePort: 30020
